backbone: resnet50
cfg: &id010 !!python/object/new:addict.addict.Dict
  args:
  - !!python/tuple
    - General
    - &id002 !!python/object/new:addict.addict.Dict
      args:
      - !!python/tuple
        - comment
        - null
      - !!python/tuple
        - seed
        - 2021
      - !!python/tuple
        - fp16
        - true
      - !!python/tuple
        - amp_level
        - O2
      - !!python/tuple
        - precision
        - 16
      - !!python/tuple
        - multi_gpu_mode
        - dp
      - !!python/tuple
        - gpus
        - &id001
          - 1
      - !!python/tuple
        - epochs
        - 200
      - !!python/tuple
        - grad_acc
        - 2
      - !!python/tuple
        - frozen_bn
        - false
      - !!python/tuple
        - patience
        - 50
      - !!python/tuple
        - server
        - test
      - !!python/tuple
        - log_path
        - /home/ylan/workspace/TransMIL-DeepGraft/logs/
      dictitems:
        amp_level: O2
        comment: null
        epochs: 200
        fp16: true
        frozen_bn: false
        gpus: *id001
        grad_acc: 2
        log_path: /home/ylan/workspace/TransMIL-DeepGraft/logs/
        multi_gpu_mode: dp
        patience: 50
        precision: 16
        seed: 2021
        server: test
      state: *id002
  - !!python/tuple
    - Data
    - &id005 !!python/object/new:addict.addict.Dict
      args:
      - !!python/tuple
        - dataset_name
        - custom
      - !!python/tuple
        - data_shuffle
        - false
      - !!python/tuple
        - data_dir
        - /home/ylan/data/DeepGraft/256_256um/
      - !!python/tuple
        - label_file
        - /home/ylan/DeepGraft/training_tables/split_bt_PAS_tcmr_viral.json
      - !!python/tuple
        - fold
        - 0
      - !!python/tuple
        - nfold
        - 3
      - !!python/tuple
        - cross_val
        - false
      - !!python/tuple
        - train_dataloader
        - &id003 !!python/object/new:addict.addict.Dict
          args:
          - !!python/tuple
            - batch_size
            - 1
          - !!python/tuple
            - num_workers
            - 8
          dictitems:
            batch_size: 1
            num_workers: 8
          state: *id003
      - !!python/tuple
        - test_dataloader
        - &id004 !!python/object/new:addict.addict.Dict
          args:
          - !!python/tuple
            - batch_size
            - 1
          - !!python/tuple
            - num_workers
            - 8
          dictitems:
            batch_size: 1
            num_workers: 8
          state: *id004
      - !!python/tuple
        - bag_size
        - 1024
      dictitems:
        bag_size: 1024
        cross_val: false
        data_dir: /home/ylan/data/DeepGraft/256_256um/
        data_shuffle: false
        dataset_name: custom
        fold: 0
        label_file: /home/ylan/DeepGraft/training_tables/split_bt_PAS_tcmr_viral.json
        nfold: 3
        test_dataloader: *id004
        train_dataloader: *id003
      state: *id005
  - !!python/tuple
    - Model
    - &id006 !!python/object/new:addict.addict.Dict
      args:
      - !!python/tuple
        - name
        - TransMIL
      - !!python/tuple
        - n_classes
        - 2
      - !!python/tuple
        - backbone
        - resnet50
      - !!python/tuple
        - in_features
        - 512
      - !!python/tuple
        - out_features
        - 512
      dictitems:
        backbone: resnet50
        in_features: 512
        n_classes: 2
        name: TransMIL
        out_features: 512
      state: *id006
  - !!python/tuple
    - Optimizer
    - &id007 !!python/object/new:addict.addict.Dict
      args:
      - !!python/tuple
        - opt
        - lookahead_radam
      - !!python/tuple
        - lr
        - 0.0002
      - !!python/tuple
        - opt_eps
        - null
      - !!python/tuple
        - opt_betas
        - null
      - !!python/tuple
        - momentum
        - null
      - !!python/tuple
        - weight_decay
        - 0.01
      dictitems:
        lr: 0.0002
        momentum: null
        opt: lookahead_radam
        opt_betas: null
        opt_eps: null
        weight_decay: 0.01
      state: *id007
  - !!python/tuple
    - Loss
    - &id008 !!python/object/new:addict.addict.Dict
      args:
      - !!python/tuple
        - base_loss
        - CrossEntropyLoss
      dictitems:
        base_loss: CrossEntropyLoss
      state: *id008
  - !!python/tuple
    - config
    - ../DeepGraft/TransMIL_resnet50_tcmr_viral.yaml
  - !!python/tuple
    - version
    - 4
  - !!python/tuple
    - epoch
    - '159'
  - !!python/tuple
    - log_path
    - &id009 !!python/object/apply:pathlib.PosixPath
      - /
      - home
      - ylan
      - workspace
      - TransMIL-DeepGraft
      - logs
      - DeepGraft
      - TransMIL
      - tcmr_viral
      - _resnet50_CrossEntropyLoss
      - lightning_logs
      - version_4
  dictitems:
    Data: *id005
    General: *id002
    Loss: *id008
    Model: *id006
    Optimizer: *id007
    config: ../DeepGraft/TransMIL_resnet50_tcmr_viral.yaml
    epoch: '159'
    log_path: *id009
    version: 4
  state: *id010
data: &id013 !!python/object/new:addict.addict.Dict
  args:
  - !!python/tuple
    - dataset_name
    - custom
  - !!python/tuple
    - data_shuffle
    - false
  - !!python/tuple
    - data_dir
    - /home/ylan/data/DeepGraft/224_128um/
  - !!python/tuple
    - label_file
    - /home/ylan/DeepGraft/training_tables/split_bt_PAS_tcmr_viral.json
  - !!python/tuple
    - fold
    - 0
  - !!python/tuple
    - nfold
    - 3
  - !!python/tuple
    - cross_val
    - false
  - !!python/tuple
    - train_dataloader
    - &id011 !!python/object/new:addict.addict.Dict
      args:
      - !!python/tuple
        - batch_size
        - 1
      - !!python/tuple
        - num_workers
        - 8
      dictitems:
        batch_size: 1
        num_workers: 8
      state: *id011
  - !!python/tuple
    - test_dataloader
    - &id012 !!python/object/new:addict.addict.Dict
      args:
      - !!python/tuple
        - batch_size
        - 1
      - !!python/tuple
        - num_workers
        - 8
      dictitems:
        batch_size: 1
        num_workers: 8
      state: *id012
  - !!python/tuple
    - bag_size
    - 1024
  dictitems:
    bag_size: 1024
    cross_val: false
    data_dir: /home/ylan/data/DeepGraft/224_128um/
    data_shuffle: false
    dataset_name: custom
    fold: 0
    label_file: /home/ylan/DeepGraft/training_tables/split_bt_PAS_tcmr_viral.json
    nfold: 3
    test_dataloader: *id012
    train_dataloader: *id011
  state: *id013
log: !!python/object/apply:pathlib.PosixPath
- /
- home
- ylan
- workspace
- TransMIL-DeepGraft
- logs
- DeepGraft
- TransMIL
- tcmr_viral
- _resnet50_CrossEntropyLoss
loss: &id014 !!python/object/new:addict.addict.Dict
  args:
  - !!python/tuple
    - base_loss
    - CrossEntropyLoss
  dictitems:
    base_loss: CrossEntropyLoss
  state: *id014
model: &id015 !!python/object/new:addict.addict.Dict
  args:
  - !!python/tuple
    - name
    - TransMIL
  - !!python/tuple
    - n_classes
    - 2
  - !!python/tuple
    - backbone
    - resnet50
  - !!python/tuple
    - in_features
    - 512
  - !!python/tuple
    - out_features
    - 512
  dictitems:
    backbone: resnet50
    in_features: 512
    n_classes: 2
    name: TransMIL
    out_features: 512
  state: *id015
optimizer: &id016 !!python/object/new:addict.addict.Dict
  args:
  - !!python/tuple
    - opt
    - lookahead_radam
  - !!python/tuple
    - lr
    - 0.0002
  - !!python/tuple
    - opt_eps
    - null
  - !!python/tuple
    - opt_betas
    - null
  - !!python/tuple
    - momentum
    - null
  - !!python/tuple
    - weight_decay
    - 0.01
  dictitems:
    lr: 0.0002
    momentum: null
    opt: lookahead_radam
    opt_betas: null
    opt_eps: null
    weight_decay: 0.01
  state: *id016
