General:
    comment: 
    seed: 2021
    fp16: True
    amp_level: O2
    precision: 16 
    multi_gpu_mode: dp
    gpus: [1]
    epochs: &epoch 1 
    grad_acc: 2
    frozen_bn: False
    patience: 2
    server: test #train #test
    log_path: logs/

Data:
    dataset_name: custom
    data_shuffle: False
    data_dir: '/home/ylan/DeepGraft/dataset/hdf5/256_256um_split/'
    label_file: '/home/ylan/DeepGraft/training_tables/split_debug.json'
    fold: 0
    nfold: 2
    cross_val: False

    train_dataloader:
        batch_size: 1 
        num_workers: 8

    test_dataloader:
        batch_size: 1
        num_workers: 8

        

Model:
    name: AttMIL
    n_classes: 2
    backbone: simple


Optimizer:
    opt: lookahead_radam
    lr: 0.0002
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss

