General:
    comment: 
    seed: 2021
    fp16: True
    amp_level: O2
    precision: 16-mixed
    multi_gpu_mode: ddp
    gpus: [0, 1]
    epochs: &epoch 1000 
    grad_acc: 2
    frozen_bn: False
    patience: 50
    server: train #train #test
    log_path: /home/ylan/workspace/TransMIL-DeepGraft/logs/

Data:
    dataset_name: custom
    data_shuffle: False
    mixup: True
    aug: True
    cache: False
    data_dir: '/home/ylan/data/DeepGraft/224_256uM_annotated/'
    label_file: '/home/ylan/data/DeepGraft/training_tables/dg_split_PAS_HE_Jones_Grocott_norm_rest_ext.json'
    fold: 1
    nfold: 3
    cross_val: False

    train_dataloader:
        batch_size: 50
        num_workers: 4

    test_dataloader:
        batch_size: 1
        num_workers: 4

Model:
    name: TransMIL
    n_classes: 2
    backbone: features
    in_features: 768
    out_features: 512


Optimizer:
    opt: radam
    lr: 0.002
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.01

Loss:
    base_loss: CrossEntropyLoss
    

