General:
    comment: 
    seed: 2021
    fp16: True
    amp_level: O2
    precision: 16 
    multi_gpu_mode: dp
    gpus: [0, 2]
    epochs: &epoch 200 
    grad_acc: 2
    frozen_bn: False
    patience: 20
    server: test #train #test
    log_path: /home/ylan/workspace/TransMIL-DeepGraft/logs/

Data:
    dataset_name: custom
    data_shuffle: False
    data_dir: '/home/ylan/data/DeepGraft/256_256um/'
    label_file: '/home/ylan/DeepGraft/training_tables/split_PAS_no_viral.json'
    fold: 1
    nfold: 4
    cross_val: False

    train_dataloader:
        batch_size: 1 
        num_workers: 8

    test_dataloader:
        batch_size: 1
        num_workers: 8

Model:
    name: TransMIL
    n_classes: 4
    backbone: efficientnet


Optimizer:
    opt: lookahead_radam
    lr: 0.0002
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss

