General:
    comment: 
    seed: 2021
    fp16: True
    amp_level: O2
    precision: 16-mixed 
    multi_gpu_mode: dp
    gpus: [0]
    epochs: &epoch 500 
    grad_acc: 2
    frozen_bn: False
    patience: 50
    server: train #train #test
    log_path: /homeStor1/ylan/workspace/TransMIL-DeepGraft/logs/

Data:
    dataset_name: custom
    feature_extractor: retccl
    data_shuffle: False
    mixup: True
    aug: True
    cache: True
    data_dir: '/homeStor1/ylan/data/DeepGraft/224_256uM_annotated/'
    label_file: '/homeStor1/ylan/data/DeepGraft/training_tables/dg_limit_50_split_PAS_HE_Jones_Grocott_rejections.json'
    # label_file: '/homeStor1/ylan/data/DeepGraft/training_tables/dg_limit_50_split_PAS_HE_Jones_Grocott_rejections.json'
    fold: 1
    nfold: 3
    cross_val: False
    bag_size: 200

    train_dataloader:
        batch_size: 64 
        num_workers: 4

    test_dataloader:
        batch_size: 1
        num_workers: 4

Model:
    name: TransMIL
    n_classes: 3
    backbone: features
    in_features: 2048
    out_features: 512


Optimizer:
    opt: radam
    lr: 0.002
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.01

Loss:
    base_loss: CrossEntropyLoss
    

